version: "3.3"

services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - USER_UID=1000
    container_name: "ruby"
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    command: ["/bin/sh"]


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
